name: Run tests with coverage

on:
  push:
    branches:
      - '**'  # This wildcard matches all branches
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    env:
      DJANGO_POLLS_SECRET_KEY: ${{ secrets.DJANGO_POLLS_SECRET_KEY }}
      DJANGO_POLLS_DB_NAME: github_actions
      DJANGO_POLLS_DB_USER: postgres
      DJANGO_POLLS_DB_PASSWORD: ${{ secrets.DJANGO_POLLS_DB_PASSWORD }}
      DJANGO_POLLS_DB_HOST: 127.0.0.1
      DJANGO_POLLS_DB_PORT: 5432
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Django migrations
      run: python manage.py migrate
    - name: Run tests (with coverage)
      run: |
        coverage run manage.py test
        coverage report --fail-under=80
        coverage xml
    - name: Report coverage to coveralls.io
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: coverage.xml
