name: Run tests with coverage

on:
  push:
    branches:
      - '**'  # This wildcard matches all branches
  pull_request:
    branches:
      - '**'  # This ensures coverage runs on PRs from any branch

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_POLLS_SECRET_KEY: ${{ secrets.DJANGO_POLLS_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run tests (with coverage)
      run: |
        coverage run manage.py test
        coverage report --fail-under=80
