name: Run tests with coverage

on:
  push:
    branches:
      - '**'  # This wildcard matches all branches
  pull_request:
    branches:
      - 'main'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DJANGO_POLLS_SECRET_KEY: ${{ secrets.DJANGO_POLLS_SECRET_KEY }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.x
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Django migrations
      run: python manage.py migrate
    - name: Run tests (with coverage)
      run: |
        coverage run manage.py test
        coverage report --fail-under=80
        coverage xml
    - name: Report coverage to coveralls.io
      uses: coverallsapp/github-action@v2
      with:
        path-to-lcov: coverage.xml
