name: Ruff (An extremely fast Python linter and code formatter)

on:
  pull_request:
    branches:
      - "*"

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: chartboost/ruff-action@v1